name: Deploy multidocker
on:
        push:
                branches:
                        - master
jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                                - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                                       # - run: docker build -t baresz/react-test -f ./client/Dockerfile.dev ./client
                                - run: docker build -t baresz/react-test -f Dockerfile.dev .
                                - run: docker run -e CI=true baresz/react-test npm test

